#pragma once

// Everything the MainViewModel implementation files talk to.
#include "viewmodels/MainViewModel.h"
#include "viewmodels/DeepLinkController.h"
#include "viewmodels/DownloadCenter.h"
#include "viewmodels/SelectedGameView.h"
#include "viewmodels/SettingsViewModel.h"
#include "models/Constants.h"
#include "models/DependencyModel.h"
#include "models/GameDepModel.h"
#include "models/GameFilterModel.h"
#include "services/ApiClient.h"
#include "services/AuthService.h"
#include "services/EntryRepository.h"
#include "services/GameManager.h"
#include "services/InstallPlanner.h"
#include "services/InstallRunner.h"
#include "services/ModuleInstaller.h"
#include "services/PathManager.h"
#include "services/PipInstaller.h"
#include "services/PipResolver.h"
#include "services/SettingsManager.h"
#include "services/UrlSchemeRegistrar.h"
