import { entry, type IconEntry } from './types'
import {
  CodeOutlined,
  TerminalOutlined,
  DataObjectOutlined,
  MemoryOutlined,
  StorageOutlined,
  DnsOutlined,
  CloudOutlined,
  CloudDownloadOutlined,
  RouterOutlined,
  WifiOutlined,
  ComputerOutlined,
  LaptopOutlined,
  PhoneAndroidOutlined,
  DevicesOutlined,
  UsbOutlined,
  CableOutlined,
  BuildOutlined,
  ConstructionOutlined,
  EngineeringOutlined,
  BugReportOutlined,
  ExtensionOutlined,
  IntegrationInstructionsOutlined,
  ApiOutlined,
  HubOutlined,
  LanOutlined,
  SecurityOutlined,
  LockOutlined,
  KeyOutlined,
  ShieldOutlined,
  FingerprintOutlined,
} from '@mui/icons-material'

export const CODE_AND_TECH_ICONS: IconEntry[] = [
  entry('CodeOutlined', CodeOutlined),
  entry('TerminalOutlined', TerminalOutlined),
  entry('DataObjectOutlined', DataObjectOutlined),
  entry('MemoryOutlined', MemoryOutlined),
  entry('StorageOutlined', StorageOutlined),
  entry('DnsOutlined', DnsOutlined),
  entry('CloudOutlined', CloudOutlined),
  entry('CloudDownloadOutlined', CloudDownloadOutlined),
  entry('RouterOutlined', RouterOutlined),
  entry('WifiOutlined', WifiOutlined),
  entry('ComputerOutlined', ComputerOutlined),
  entry('LaptopOutlined', LaptopOutlined),
  entry('PhoneAndroidOutlined', PhoneAndroidOutlined),
  entry('DevicesOutlined', DevicesOutlined),
  entry('UsbOutlined', UsbOutlined),
  entry('CableOutlined', CableOutlined),
  entry('BuildOutlined', BuildOutlined),
  entry('ConstructionOutlined', ConstructionOutlined),
  entry('EngineeringOutlined', EngineeringOutlined),
  entry('BugReportOutlined', BugReportOutlined),
  entry('ExtensionOutlined', ExtensionOutlined),
  entry('IntegrationInstructionsOutlined', IntegrationInstructionsOutlined),
  entry('ApiOutlined', ApiOutlined),
  entry('HubOutlined', HubOutlined),
  entry('LanOutlined', LanOutlined),
  entry('SecurityOutlined', SecurityOutlined),
  entry('LockOutlined', LockOutlined),
  entry('KeyOutlined', KeyOutlined),
  entry('ShieldOutlined', ShieldOutlined),
  entry('FingerprintOutlined', FingerprintOutlined),
]
