import { entry, type IconEntry } from './types'
import {
  ArticleOutlined,
  DescriptionOutlined,
  BookOutlined,
  MenuBookOutlined,
  LibraryBooksOutlined,
  NewspaperOutlined,
  FeedOutlined,
  NoteOutlined,
  StickyNote2Outlined,
  EditOutlined,
  CreateOutlined,
  DrawOutlined,
  BrushOutlined,
  PaletteOutlined,
  FormatQuoteOutlined,
  SummarizeOutlined,
  TopicOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  Inventory2Outlined,
  ArchiveOutlined,
  CategoryOutlined,
  LabelOutlined,
  TagOutlined,
  NotesOutlined,
  SubjectOutlined,
  TitleOutlined,
  TextSnippetOutlined,
} from '@mui/icons-material'

export const CONTENT_ICONS: IconEntry[] = [
  entry('ArticleOutlined', ArticleOutlined),
  entry('DescriptionOutlined', DescriptionOutlined),
  entry('BookOutlined', BookOutlined),
  entry('MenuBookOutlined', MenuBookOutlined),
  entry('LibraryBooksOutlined', LibraryBooksOutlined),
  entry('NewspaperOutlined', NewspaperOutlined),
  entry('FeedOutlined', FeedOutlined),
  entry('NoteOutlined', NoteOutlined),
  entry('StickyNote2Outlined', StickyNote2Outlined),
  entry('EditOutlined', EditOutlined),
  entry('CreateOutlined', CreateOutlined),
  entry('DrawOutlined', DrawOutlined),
  entry('BrushOutlined', BrushOutlined),
  entry('PaletteOutlined', PaletteOutlined),
  entry('FormatQuoteOutlined', FormatQuoteOutlined),
  entry('SummarizeOutlined', SummarizeOutlined),
  entry('TopicOutlined', TopicOutlined),
  entry('FolderOutlined', FolderOutlined),
  entry('FolderOpenOutlined', FolderOpenOutlined),
  entry('Inventory2Outlined', Inventory2Outlined),
  entry('ArchiveOutlined', ArchiveOutlined),
  entry('CategoryOutlined', CategoryOutlined),
  entry('LabelOutlined', LabelOutlined),
  entry('TagOutlined', TagOutlined),
  entry('NotesOutlined', NotesOutlined),
  entry('SubjectOutlined', SubjectOutlined),
  entry('TitleOutlined', TitleOutlined),
  entry('TextSnippetOutlined', TextSnippetOutlined),
]
