import { entry, type IconEntry } from './types'
import {
  DownloadOutlined,
  UploadOutlined,
  AttachmentOutlined,
  AttachFileOutlined,
  PrintOutlined,
  SaveOutlined,
  BackupOutlined,
  SyncOutlined,
  RefreshOutlined,
  HistoryOutlined,
  RestoreOutlined,
  UndoOutlined,
  AddOutlined,
  RemoveOutlined,
  DeleteOutlined,
  ContentCopyOutlined,
  QrCodeOutlined,
  BookmarksOutlined,
  InboxOutlined,
  OutboxOutlined,
  SendOutlined,
  PublishOutlined,
  UnarchiveOutlined,
  LayersOutlined,
  GridViewOutlined,
  ViewListOutlined,
  ViewModuleOutlined,
  ViewQuiltOutlined,
} from '@mui/icons-material'

export const FILES_AND_ACTIONS_ICONS: IconEntry[] = [
  entry('DownloadOutlined', DownloadOutlined),
  entry('UploadOutlined', UploadOutlined),
  entry('AttachmentOutlined', AttachmentOutlined),
  entry('AttachFileOutlined', AttachFileOutlined),
  entry('PrintOutlined', PrintOutlined),
  entry('SaveOutlined', SaveOutlined),
  entry('BackupOutlined', BackupOutlined),
  entry('SyncOutlined', SyncOutlined),
  entry('RefreshOutlined', RefreshOutlined),
  entry('HistoryOutlined', HistoryOutlined),
  entry('RestoreOutlined', RestoreOutlined),
  entry('UndoOutlined', UndoOutlined),
  entry('AddOutlined', AddOutlined),
  entry('RemoveOutlined', RemoveOutlined),
  entry('DeleteOutlined', DeleteOutlined),
  entry('ContentCopyOutlined', ContentCopyOutlined),
  entry('QrCodeOutlined', QrCodeOutlined),
  entry('BookmarksOutlined', BookmarksOutlined),
  entry('InboxOutlined', InboxOutlined),
  entry('OutboxOutlined', OutboxOutlined),
  entry('SendOutlined', SendOutlined),
  entry('PublishOutlined', PublishOutlined),
  entry('UnarchiveOutlined', UnarchiveOutlined),
  entry('LayersOutlined', LayersOutlined),
  entry('GridViewOutlined', GridViewOutlined),
  entry('ViewListOutlined', ViewListOutlined),
  entry('ViewModuleOutlined', ViewModuleOutlined),
  entry('ViewQuiltOutlined', ViewQuiltOutlined),
]
