import { entry, type IconEntry } from './types'
import {
  SportsEsportsOutlined,
  VideogameAssetOutlined,
  ToysOutlined,
  SportsGolfOutlined,
  SportsSoccerOutlined,
  SportsBasketballOutlined,
  SportsTennisOutlined,
  SportsMotorsportsOutlined,
  PoolOutlined,
  FitnessCenterOutlined,
  KayakingOutlined,
  SurfingOutlined,
  EmojiEventsOutlined,
  TheaterComedyOutlined,
  GamesOutlined,
  StadiumOutlined,
  SportsCricketOutlined,
  SportsRugbyOutlined,
  SportsHandballOutlined,
  SportsMmaOutlined,
  SkateboardingOutlined,
  SleddingOutlined,
  SnowboardingOutlined,
} from '@mui/icons-material'

export const GAMES_AND_SPORT_ICONS: IconEntry[] = [
  entry('SportsEsportsOutlined', SportsEsportsOutlined),
  entry('VideogameAssetOutlined', VideogameAssetOutlined),
  entry('ToysOutlined', ToysOutlined),
  entry('SportsGolfOutlined', SportsGolfOutlined),
  entry('SportsSoccerOutlined', SportsSoccerOutlined),
  entry('SportsBasketballOutlined', SportsBasketballOutlined),
  entry('SportsTennisOutlined', SportsTennisOutlined),
  entry('SportsMotorsportsOutlined', SportsMotorsportsOutlined),
  entry('PoolOutlined', PoolOutlined),
  entry('FitnessCenterOutlined', FitnessCenterOutlined),
  entry('KayakingOutlined', KayakingOutlined),
  entry('SurfingOutlined', SurfingOutlined),
  entry('EmojiEventsOutlined', EmojiEventsOutlined),
  entry('TheaterComedyOutlined', TheaterComedyOutlined),
  entry('GamesOutlined', GamesOutlined),
  entry('StadiumOutlined', StadiumOutlined),
  entry('SportsCricketOutlined', SportsCricketOutlined),
  entry('SportsRugbyOutlined', SportsRugbyOutlined),
  entry('SportsHandballOutlined', SportsHandballOutlined),
  entry('SportsMmaOutlined', SportsMmaOutlined),
  entry('SkateboardingOutlined', SkateboardingOutlined),
  entry('SleddingOutlined', SleddingOutlined),
  entry('SnowboardingOutlined', SnowboardingOutlined),
]
