import { entry, type IconEntry } from './types'
import {
  YardOutlined,
  GrassOutlined,
  ParkOutlined,
  ForestOutlined,
  SpaOutlined,
  PetsOutlined,
  LocalFloristOutlined,
  AgricultureOutlined,
  CottageOutlined,
  HouseOutlined,
  CabinOutlined,
  BedOutlined,
  KitchenOutlined,
  RestaurantOutlined,
  LocalCafeOutlined,
  CookieOutlined,
  FastfoodOutlined,
  LocalBarOutlined,
  ShowerOutlined,
  WeekendOutlined,
  ChairOutlined,
  BathtubOutlined,
  NatureOutlined,
  NaturePeopleOutlined,
} from '@mui/icons-material'

export const HOME_AND_NATURE_ICONS: IconEntry[] = [
  entry('YardOutlined', YardOutlined),
  entry('GrassOutlined', GrassOutlined),
  entry('ParkOutlined', ParkOutlined),
  entry('ForestOutlined', ForestOutlined),
  entry('SpaOutlined', SpaOutlined),
  entry('PetsOutlined', PetsOutlined),
  entry('LocalFloristOutlined', LocalFloristOutlined),
  entry('AgricultureOutlined', AgricultureOutlined),
  entry('CottageOutlined', CottageOutlined),
  entry('HouseOutlined', HouseOutlined),
  entry('CabinOutlined', CabinOutlined),
  entry('BedOutlined', BedOutlined),
  entry('KitchenOutlined', KitchenOutlined),
  entry('RestaurantOutlined', RestaurantOutlined),
  entry('LocalCafeOutlined', LocalCafeOutlined),
  entry('CookieOutlined', CookieOutlined),
  entry('FastfoodOutlined', FastfoodOutlined),
  entry('LocalBarOutlined', LocalBarOutlined),
  entry('ShowerOutlined', ShowerOutlined),
  entry('WeekendOutlined', WeekendOutlined),
  entry('ChairOutlined', ChairOutlined),
  entry('BathtubOutlined', BathtubOutlined),
  entry('NatureOutlined', NatureOutlined),
  entry('NaturePeopleOutlined', NaturePeopleOutlined),
]
