import { entry, type IconEntry } from './types'
import {
  CalculateOutlined,
  FunctionsOutlined,
  NumbersOutlined,
  PercentOutlined,
  PinOutlined,
  ScienceOutlined,
  BiotechOutlined,
  PsychologyOutlined,
  LightbulbOutlined,
  SchemaOutlined,
  AnalyticsOutlined,
  BarChartOutlined,
  PieChartOutlined,
  ShowChartOutlined,
  TimelineOutlined,
  InsightsOutlined,
  QueryStatsOutlined,
  SortOutlined,
  FilterListOutlined,
  AbcOutlined,
  SpeedOutlined,
  TimerOutlined,
  CasinoOutlined,
  TuneOutlined,
  StraightenOutlined,
  SquareFootOutlined,
  ArchitectureOutlined,
  RuleOutlined,
} from '@mui/icons-material'

export const MATHS_AND_SCIENCE_ICONS: IconEntry[] = [
  entry('CalculateOutlined', CalculateOutlined),
  entry('FunctionsOutlined', FunctionsOutlined),
  entry('NumbersOutlined', NumbersOutlined),
  entry('PercentOutlined', PercentOutlined),
  entry('PinOutlined', PinOutlined),
  entry('ScienceOutlined', ScienceOutlined),
  entry('BiotechOutlined', BiotechOutlined),
  entry('PsychologyOutlined', PsychologyOutlined),
  entry('LightbulbOutlined', LightbulbOutlined),
  entry('SchemaOutlined', SchemaOutlined),
  entry('AnalyticsOutlined', AnalyticsOutlined),
  entry('BarChartOutlined', BarChartOutlined),
  entry('PieChartOutlined', PieChartOutlined),
  entry('ShowChartOutlined', ShowChartOutlined),
  entry('TimelineOutlined', TimelineOutlined),
  entry('InsightsOutlined', InsightsOutlined),
  entry('QueryStatsOutlined', QueryStatsOutlined),
  entry('SortOutlined', SortOutlined),
  entry('FilterListOutlined', FilterListOutlined),
  entry('AbcOutlined', AbcOutlined),
  entry('SpeedOutlined', SpeedOutlined),
  entry('TimerOutlined', TimerOutlined),
  entry('CasinoOutlined', CasinoOutlined),
  entry('TuneOutlined', TuneOutlined),
  entry('StraightenOutlined', StraightenOutlined),
  entry('SquareFootOutlined', SquareFootOutlined),
  entry('ArchitectureOutlined', ArchitectureOutlined),
  entry('RuleOutlined', RuleOutlined),
]
