import { entry, type IconEntry } from './types'
import {
  PhotoOutlined,
  PhotoLibraryOutlined,
  PhotoCameraOutlined,
  CollectionsOutlined,
  ImageOutlined,
  VideocamOutlined,
  MovieOutlined,
  OndemandVideoOutlined,
  MusicNoteOutlined,
  HeadphonesOutlined,
  MicOutlined,
  PodcastsOutlined,
  RadioOutlined,
  AlbumOutlined,
  GraphicEqOutlined,
  PlayCircleOutlined,
  SlideshowOutlined,
  TheatersOutlined,
  CameraOutlined,
  CameraAltOutlined,
  PanoramaOutlined,
  LandscapeOutlined,
  WallpaperOutlined,
  GifOutlined,
  LiveTvOutlined,
  VideoLibraryOutlined,
  PianoOutlined,
  AudiotrackOutlined,
} from '@mui/icons-material'

export const MEDIA_ICONS: IconEntry[] = [
  entry('PhotoOutlined', PhotoOutlined),
  entry('PhotoLibraryOutlined', PhotoLibraryOutlined),
  entry('PhotoCameraOutlined', PhotoCameraOutlined),
  entry('CollectionsOutlined', CollectionsOutlined),
  entry('ImageOutlined', ImageOutlined),
  entry('VideocamOutlined', VideocamOutlined),
  entry('MovieOutlined', MovieOutlined),
  entry('OndemandVideoOutlined', OndemandVideoOutlined),
  entry('MusicNoteOutlined', MusicNoteOutlined),
  entry('HeadphonesOutlined', HeadphonesOutlined),
  entry('MicOutlined', MicOutlined),
  entry('PodcastsOutlined', PodcastsOutlined),
  entry('RadioOutlined', RadioOutlined),
  entry('AlbumOutlined', AlbumOutlined),
  entry('GraphicEqOutlined', GraphicEqOutlined),
  entry('PlayCircleOutlined', PlayCircleOutlined),
  entry('SlideshowOutlined', SlideshowOutlined),
  entry('TheatersOutlined', TheatersOutlined),
  entry('CameraOutlined', CameraOutlined),
  entry('CameraAltOutlined', CameraAltOutlined),
  entry('PanoramaOutlined', PanoramaOutlined),
  entry('LandscapeOutlined', LandscapeOutlined),
  entry('WallpaperOutlined', WallpaperOutlined),
  entry('GifOutlined', GifOutlined),
  entry('LiveTvOutlined', LiveTvOutlined),
  entry('VideoLibraryOutlined', VideoLibraryOutlined),
  entry('PianoOutlined', PianoOutlined),
  entry('AudiotrackOutlined', AudiotrackOutlined),
]
