import { entry, type IconEntry } from './types'
import {
  HomeOutlined,
  MenuOutlined,
  ExploreOutlined,
  MapOutlined,
  PlaceOutlined,
  PublicOutlined,
  LanguageOutlined,
  SearchOutlined,
  DashboardOutlined,
  AppsOutlined,
  LinkOutlined,
  OpenInNewOutlined,
  ArrowForwardOutlined,
  StarOutlined,
  FavoriteOutlined,
  BookmarkOutlined,
  FlagOutlined,
  InfoOutlined,
  HelpOutlined,
  SettingsOutlined,
  NotificationsOutlined,
  VisibilityOutlined,
  BoltOutlined,
  RocketLaunchOutlined,
  AnchorOutlined,
  MyLocationOutlined,
  PushPinOutlined,
} from '@mui/icons-material'

export const NAVIGATION_ICONS: IconEntry[] = [
  entry('HomeOutlined', HomeOutlined),
  entry('MenuOutlined', MenuOutlined),
  entry('ExploreOutlined', ExploreOutlined),
  entry('MapOutlined', MapOutlined),
  entry('PlaceOutlined', PlaceOutlined),
  entry('PublicOutlined', PublicOutlined),
  entry('LanguageOutlined', LanguageOutlined),
  entry('SearchOutlined', SearchOutlined),
  entry('DashboardOutlined', DashboardOutlined),
  entry('AppsOutlined', AppsOutlined),
  entry('LinkOutlined', LinkOutlined),
  entry('OpenInNewOutlined', OpenInNewOutlined),
  entry('ArrowForwardOutlined', ArrowForwardOutlined),
  entry('StarOutlined', StarOutlined),
  entry('FavoriteOutlined', FavoriteOutlined),
  entry('BookmarkOutlined', BookmarkOutlined),
  entry('FlagOutlined', FlagOutlined),
  entry('InfoOutlined', InfoOutlined),
  entry('HelpOutlined', HelpOutlined),
  entry('SettingsOutlined', SettingsOutlined),
  entry('NotificationsOutlined', NotificationsOutlined),
  entry('VisibilityOutlined', VisibilityOutlined),
  entry('BoltOutlined', BoltOutlined),
  entry('RocketLaunchOutlined', RocketLaunchOutlined),
  entry('AnchorOutlined', AnchorOutlined),
  entry('MyLocationOutlined', MyLocationOutlined),
  entry('PushPinOutlined', PushPinOutlined),
]
