import { entry, type IconEntry } from './types'
import {
  PersonOutlined,
  PeopleOutlined,
  GroupOutlined,
  GroupsOutlined,
  FaceOutlined,
  MailOutlined,
  EmailOutlined,
  ChatOutlined,
  ForumOutlined,
  CommentOutlined,
  QuestionAnswerOutlined,
  CallOutlined,
  ContactsOutlined,
  ContactMailOutlined,
  ShareOutlined,
  ThumbUpOutlined,
  HandshakeOutlined,
  Diversity3Outlined,
  CakeOutlined,
  CelebrationOutlined,
  EmojiEmotionsOutlined,
  SentimentSatisfiedOutlined,
  BadgeOutlined,
  VerifiedOutlined,
  AdminPanelSettingsOutlined,
  SupervisorAccountOutlined,
  CampaignOutlined,
} from '@mui/icons-material'

export const PEOPLE_AND_SOCIAL_ICONS: IconEntry[] = [
  entry('PersonOutlined', PersonOutlined),
  entry('PeopleOutlined', PeopleOutlined),
  entry('GroupOutlined', GroupOutlined),
  entry('GroupsOutlined', GroupsOutlined),
  entry('FaceOutlined', FaceOutlined),
  entry('MailOutlined', MailOutlined),
  entry('EmailOutlined', EmailOutlined),
  entry('ChatOutlined', ChatOutlined),
  entry('ForumOutlined', ForumOutlined),
  entry('CommentOutlined', CommentOutlined),
  entry('QuestionAnswerOutlined', QuestionAnswerOutlined),
  entry('CallOutlined', CallOutlined),
  entry('ContactsOutlined', ContactsOutlined),
  entry('ContactMailOutlined', ContactMailOutlined),
  entry('ShareOutlined', ShareOutlined),
  entry('ThumbUpOutlined', ThumbUpOutlined),
  entry('HandshakeOutlined', HandshakeOutlined),
  entry('Diversity3Outlined', Diversity3Outlined),
  entry('CakeOutlined', CakeOutlined),
  entry('CelebrationOutlined', CelebrationOutlined),
  entry('EmojiEmotionsOutlined', EmojiEmotionsOutlined),
  entry('SentimentSatisfiedOutlined', SentimentSatisfiedOutlined),
  entry('BadgeOutlined', BadgeOutlined),
  entry('VerifiedOutlined', VerifiedOutlined),
  entry('AdminPanelSettingsOutlined', AdminPanelSettingsOutlined),
  entry('SupervisorAccountOutlined', SupervisorAccountOutlined),
  entry('CampaignOutlined', CampaignOutlined),
]
