import { entry, type IconEntry } from './types'
import {
  ShoppingCartOutlined,
  ShoppingBagOutlined,
  StoreOutlined,
  StorefrontOutlined,
  PaymentsOutlined,
  CreditCardOutlined,
  AttachMoneyOutlined,
  SavingsOutlined,
  WorkOutlined,
  BusinessOutlined,
  SchoolOutlined,
  ApartmentOutlined,
  AccountBalanceOutlined,
  ReceiptOutlined,
  SellOutlined,
  LocalOfferOutlined,
  DiscountOutlined,
  RedeemOutlined,
  CardGiftcardOutlined,
  HandymanOutlined,
  GavelOutlined,
  HardwareOutlined,
  FactoryOutlined,
  WarehouseOutlined,
} from '@mui/icons-material'

export const SHOP_AND_WORK_ICONS: IconEntry[] = [
  entry('ShoppingCartOutlined', ShoppingCartOutlined),
  entry('ShoppingBagOutlined', ShoppingBagOutlined),
  entry('StoreOutlined', StoreOutlined),
  entry('StorefrontOutlined', StorefrontOutlined),
  entry('PaymentsOutlined', PaymentsOutlined),
  entry('CreditCardOutlined', CreditCardOutlined),
  entry('AttachMoneyOutlined', AttachMoneyOutlined),
  entry('SavingsOutlined', SavingsOutlined),
  entry('WorkOutlined', WorkOutlined),
  entry('BusinessOutlined', BusinessOutlined),
  entry('SchoolOutlined', SchoolOutlined),
  entry('ApartmentOutlined', ApartmentOutlined),
  entry('AccountBalanceOutlined', AccountBalanceOutlined),
  entry('ReceiptOutlined', ReceiptOutlined),
  entry('SellOutlined', SellOutlined),
  entry('LocalOfferOutlined', LocalOfferOutlined),
  entry('DiscountOutlined', DiscountOutlined),
  entry('RedeemOutlined', RedeemOutlined),
  entry('CardGiftcardOutlined', CardGiftcardOutlined),
  entry('HandymanOutlined', HandymanOutlined),
  entry('GavelOutlined', GavelOutlined),
  entry('HardwareOutlined', HardwareOutlined),
  entry('FactoryOutlined', FactoryOutlined),
  entry('WarehouseOutlined', WarehouseOutlined),
]
