import { entry, type IconEntry } from './types'
import {
  TrainOutlined,
  TramOutlined,
  SubwayOutlined,
  DirectionsRailwayOutlined,
  DirectionsBusOutlined,
  DirectionsCarOutlined,
  DirectionsBikeOutlined,
  TwoWheelerOutlined,
  FlightOutlined,
  FlightTakeoffOutlined,
  FlightLandOutlined,
  AirplanemodeActiveOutlined,
  SailingOutlined,
  DirectionsBoatOutlined,
  LocalShippingOutlined,
  CommuteOutlined,
  ElectricBikeOutlined,
  ElectricCarOutlined,
  PedalBikeOutlined,
  TrafficOutlined,
  RouteOutlined,
  NavigationOutlined,
  TerrainOutlined,
  HikingOutlined,
} from '@mui/icons-material'

export const TRANSPORT_ICONS: IconEntry[] = [
  entry('TrainOutlined', TrainOutlined),
  entry('TramOutlined', TramOutlined),
  entry('SubwayOutlined', SubwayOutlined),
  entry('DirectionsRailwayOutlined', DirectionsRailwayOutlined),
  entry('DirectionsBusOutlined', DirectionsBusOutlined),
  entry('DirectionsCarOutlined', DirectionsCarOutlined),
  entry('DirectionsBikeOutlined', DirectionsBikeOutlined),
  entry('TwoWheelerOutlined', TwoWheelerOutlined),
  entry('FlightOutlined', FlightOutlined),
  entry('FlightTakeoffOutlined', FlightTakeoffOutlined),
  entry('FlightLandOutlined', FlightLandOutlined),
  entry('AirplanemodeActiveOutlined', AirplanemodeActiveOutlined),
  entry('SailingOutlined', SailingOutlined),
  entry('DirectionsBoatOutlined', DirectionsBoatOutlined),
  entry('LocalShippingOutlined', LocalShippingOutlined),
  entry('CommuteOutlined', CommuteOutlined),
  entry('ElectricBikeOutlined', ElectricBikeOutlined),
  entry('ElectricCarOutlined', ElectricCarOutlined),
  entry('PedalBikeOutlined', PedalBikeOutlined),
  entry('TrafficOutlined', TrafficOutlined),
  entry('RouteOutlined', RouteOutlined),
  entry('NavigationOutlined', NavigationOutlined),
  entry('TerrainOutlined', TerrainOutlined),
  entry('HikingOutlined', HikingOutlined),
]
