import { entry, type IconEntry } from './types'
import {
  WbSunnyOutlined,
  NightlightOutlined,
  ThunderstormOutlined,
  AcUnitOutlined,
  WaterOutlined,
  LocalFireDepartmentOutlined,
  ScheduleOutlined,
  EventOutlined,
  CalendarMonthOutlined,
  TodayOutlined,
  HourglassEmptyOutlined,
  AlarmOutlined,
  WatchOutlined,
  BedtimeOutlined,
  UmbrellaOutlined,
  AirOutlined,
  WavesOutlined,
  ThermostatOutlined,
  Brightness4Outlined,
  LightModeOutlined,
  DarkModeOutlined,
} from '@mui/icons-material'

export const WEATHER_AND_TIME_ICONS: IconEntry[] = [
  entry('WbSunnyOutlined', WbSunnyOutlined),
  entry('NightlightOutlined', NightlightOutlined),
  entry('ThunderstormOutlined', ThunderstormOutlined),
  entry('AcUnitOutlined', AcUnitOutlined),
  entry('WaterOutlined', WaterOutlined),
  entry('LocalFireDepartmentOutlined', LocalFireDepartmentOutlined),
  entry('ScheduleOutlined', ScheduleOutlined),
  entry('EventOutlined', EventOutlined),
  entry('CalendarMonthOutlined', CalendarMonthOutlined),
  entry('TodayOutlined', TodayOutlined),
  entry('HourglassEmptyOutlined', HourglassEmptyOutlined),
  entry('AlarmOutlined', AlarmOutlined),
  entry('WatchOutlined', WatchOutlined),
  entry('BedtimeOutlined', BedtimeOutlined),
  entry('UmbrellaOutlined', UmbrellaOutlined),
  entry('AirOutlined', AirOutlined),
  entry('WavesOutlined', WavesOutlined),
  entry('ThermostatOutlined', ThermostatOutlined),
  entry('Brightness4Outlined', Brightness4Outlined),
  entry('LightModeOutlined', LightModeOutlined),
  entry('DarkModeOutlined', DarkModeOutlined),
]
